### ISSUE TITLE
csirtg-smrt not starting w/ error: AttributeError: unknown attribute: "days"

### ISSUE THREAD

**Issue by dwdixon** [sfinlon/cif-docker#2]
As discussed today, it seems this is related to the version of the python arrow library, when reverting to arrow 0.14.2 (from 0.14.6) the error goes away and the csirtg-smrt service appears to start up as expected.  When using arrow 0.14.6 the csirtg-smrt service dies out and fails:

```
2019-08-29 18:33:36,227 DEBG 'csirtg-smrt' stderr output:
Traceback (most recent call last):
  File "/usr/local/bin/csirtg-smrt", line 11, in <module>
    load_entry_point('csirtg-smrt==1.0.7', 'console_scripts', 'csirtg-smrt')()
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/smrt.py", line 446, in main
    goback = arrow.utcnow().replace(days=-int(goback))
  File "/usr/local/lib/python2.7/dist-packages/arrow/arrow.py", line 602, in replace
```

**Comment by sfinlon** [comment]
this is due do a change in arrow's functionality between 0.14.2 and 0.15.2, pinned version to 0.14.2 in csirtg-smrt and csirtg-indicator
